### ISSUE TITLE
Gradle xsd2java - clean build

### ISSUE THREAD

**Issue by tempvchitti** [nilsmagnus/wsdl2java#28]
Hi
When I run gradle clean build on the project which uses xsd2java  plugin, I get this error

* What went wrong:
Execution failed for task ':ddx-common-rest-api:compileJava'.
> com/sun/tools/javac/util/Log$PrefixKind

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':ddx-common-rest-api:compileJava'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:158)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:155)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:36)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:103)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:97)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:97)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:102)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:47)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:32)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.NoClassDefFoundError: com/sun/tools/javac/util/Log$PrefixKind
	at com.sun.tools.javac.main.Main.bugMessage(Main.java:587)
	at com.sun.tools.javac.main.Main.compile(Main.java:568)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:45)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:101)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:50)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:36)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:157)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:139)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:93)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:243)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:230)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 68 more
Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.util.Log$PrefixKind
	... 89 more

But , when i run just build task, i do not see any error.

I think the plugin is broken when used 'clean' command.

**Comment by nilsmagnus** [comment]
What version of the plugin are you running?

**Comment by marchc** [comment]
Hi Nils

Plugin version 0.6, cradle file attached,

I comment it out and put it back in when I want it to work

Thanks

Chris


buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'no.nils:wsdl2java:0.6'
    }
}

apply plugin: 'java'

task sourcesJar(type: Jar, dependsOn: classes) {
    classifier = 'sources'
    from sourceSets.main.allSource
}

jar {
    manifest.attributes provider: 'Travel Technology Systems Ltd'
    archivesBaseName = 'io.travelthing.messages'
    from sourceSets.main.allJava
}

version = '1.0'

compileJava {
    sourceCompatibility = 1.7;
    targetCompatibility = 1.7;
}

dependencies {

    compile ":io.ttsltd.core.utils",
            ":io.ttsltd.core.orm",
            "com.google.guava:guava:$guavaVersion@jar",
            "com.intellij:annotations:$intelijAnnotationsVersion@jar",
            "commons-collections:commons-collections:$commonsCollectionsVersion@jar",
            "javax.validation:validation-api:$javaxValidationVersion@jar",
            "org.apache.commons:commons-lang3:$commonsLang3Version@jar",
            "org.hibernate.javax.persistence:hibernate-jpa-2.1-api:$hibernateJpa2Version@jar",
            "org.projectlombok:lombok:$lombokVersion@jar",
            "org.slf4j:slf4j-api:$slf4jVersion@jar"

    testCompile "junit:junit:$junitVersion@jar",
            "org.hamcrest:hamcrest-all:$hamCrestVersion@jar",
            "com.jayway.jsonpath:json-path:$jaywayJsonPathVersion@jar"

    testRuntime "ch.qos.logback:logback-core:$logbackVersion@jar",
            "net.minidev:json-smart:$minidevJsonSmartVersion@jar",
            "net.minidev:asm:$minidevAsmVersion@jar",
            "ch.qos.logback:logback-classic:$logbackVersion@jar",
            "org.slf4j:log4j-over-slf4j:$log4jOverSlf4jVersion@jar"

}

//apply plugin: 'no.nils.wsdl2java'
//
//wsdl2java {
//    wsdlsToGenerate = [
//            ["$projectDir/src/main/resources/io/travelthing/soa/v2015_01/wsdl/TravelThingServices.wsdl"]
//    ]
//    generatedWsdlDir = file("$projectDir/generated")
//    wsdlDir = file("$projectDir/src/main/resources/io/travelthing/soa/v2015_01/wsdl")
//    cxfVersion = "3.0.1"
//}
//
//task soaClean(type: Delete) {
//    delete fileTree(dir: "src/main/java/io/travelthing/soa")
//}
//task soaCopy(type: Copy) {
//    from 'generated'
//    into 'src/main/java'
//}

Chris March | ceo
travel technology systems
2 Nile Close, Riversway, Preston. Lancashire. PR2 2XU
t +44 (0) 1772 766800 |» m +44 (0) 7747 023000 |» e chris.march@ttsltd.com<mailto:chris.march@ttsltd.com> |» w www.ttsltd.com<http://www.ttsltd.com/>

[http://www.ttsltd.com/content/themes/tts/images/tts-email-logo.png]
tomorrow's software today!
________________________________
please consider the environment before printing this email

This Email may contain information of a confidential and/or privileged nature.
The information transmitted is intended only for the benefit of the person or entity to which it is addressed and must not be copied or forwarded without the sender's express permission.
This Email does not reflect the views or opinions of Travel Technology Systems
This Email is without prejudice.
This Email does not constitute an agreement either explicitly or implicitly with Travel Technology Systems

From: Nils Larsgård
Reply-To: nilsmagnus/wsdl2java
Date: Wednesday, 7 October 2015 at 13:46
To: nilsmagnus/wsdl2java
Subject: Re: [wsdl2java] Gradle xsd2java - clean build (#28)


What version of the plugin are you running?

**Comment by iceddante** [comment]
I'm currently experiencing this problem with 
`apply plugin: 'no.nils.wsdl2java'`
Is the proper solution to use a specific version?

Thanks!

**Comment by cheolgook** [comment]
Had the same issue and found this workaround using `fork` option for `compileJava` tasks to let gradle use JDK's javac compiler.

    tasks.withType(JavaCompile) {
        options.fork = true
    }

https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.JavaCompile.html
