### ISSUE TITLE
Namespace mapping

### ISSUE THREAD

**Issue by YuryZj** [nilsmagnus/wsdl2java#52]
I've been trying 
wsdl2java{ 
  wsdlsToGenerate = [
   ["-p",'http://some.namespace.ru=my.package.name', "$wsdlDir/services/equeue/wsdl/equeue.wsdl"]
  ]
wsdlDir = file("$projectDir/src/main/resources") 
generatedWsdlDir = file("$projectDir/target/gen-java")
 locale = Locale.ENGLISH 
}
I get an error, , stack trace below.
Thanks so much!

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':integration:wsdl2java'.
...
Caused by: org.gradle.api.UncheckedIOException: Could not normalize path for file 'C:\work\projects\gradle_project\project\integration\target\gen-java\http://some.namespace.
        at org.gradle.api.internal.file.AbstractFileResolver.normalise(AbstractFileResolver.java:141)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:83)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:63)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext$FileCollectionConverter.convertInto(DefaultFileCollectionResolveContext.java:177)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResolve(DefaultFileCollectionResolveContext.java:138)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolveAsFileCollections(DefaultFileCollectionResolveContext.java:85)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext$FileCollectionConverter.convertInto(DefaultFileCollectionResolveContext.java:161)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResolve(DefaultFileCollectionResolveContext.java:102)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolveAsFileCollections(DefaultFileCollectionResolveContext.java:85)
        at org.gradle.api.internal.file.CompositeFileCollection.getSourceCollections(CompositeFileCollection.java:162)
        at org.gradle.api.internal.file.CompositeFileCollection.getFiles(CompositeFileCollection.java:45)
        at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:65)
        at org.gradle.api.internal.file.copy.DeleteActionImpl.delete(DeleteActionImpl.java:40)
        at org.gradle.api.internal.file.DefaultFileOperations.delete(DefaultFileOperations.java:130)
        at org.gradle.api.internal.project.AbstractProject.delete(AbstractProject.java:690)
        at no.nils.wsdl2java.Wsdl2JavaTask.deleteOutputFolders(Wsdl2JavaTask.groovy:127)
        at no.nils.wsdl2java.Wsdl2JavaTask.wsdl2java(Wsdl2JavaTask.groovy:55)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
...
Caused by: java.io.IOException:

**Comment by YuryZj** [comment]
In the version 0.11-SNAPSHOT of the problem is solved.
